export const product = {
  SET_PRODUCTS_LOADING: "SET_PRODUCTS_LOADING",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCTS_RESULTS: "SET_PRODUCTS_RESULTS",
};

export const category = {
  SET_CATEGORIES_LOADING: "SET_CATEGORIES_LOADING",
  SET_CATEGORIES: "SET_CATEGORIES",
};
